# =============================================
# CONFIGURACIÓN H2 (base de datos en memoria)
# =============================================
spring.datasource.url=jdbc:h2:mem:ms_archivos;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Inicialización de datos
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Puerto
server.port=8080

# Actuator
management.endpoints.web.exposure.include=health,info

# =============================================
# CONFIGURACIÓN AWS S3
# =============================================
aws.s3.bucket-name=bucket-exp1-s3
aws.region=${AWS_REGION:us-east-1}

# =============================================
# CONFIGURACIÓN EFS
# Dentro del contenedor el EFS se monta en /app/efs
# (docker run -v /mnt/efs:/app/efs ...)
# =============================================
efs.mount-path=/app/efs

# Spring Cloud AWS - deshabilitar autoconfiguración



# =============================================
# CONFIGURACIÓN SEGURIDAD - AZURE AD B2C (JWT)
# =============================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://guiasdespacho2.b2clogin.com/tfp/43c80967-57ec-45e0-a2e2-57d0859a95d1/b2c_1_registro_login/v2.0/
